package test.bwei.com.servicedemon;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import test.bwei.com.servicedemon.entity.DownloadEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DOWNLOAD_ENTITY".
*/
public class DownloadEntityDao extends AbstractDao<DownloadEntity, Long> {

    public static final String TABLENAME = "DOWNLOAD_ENTITY";

    /**
     * Properties of entity DownloadEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property ThreadId = new Property(1, String.class, "threadId", false, "THREAD_ID");
        public final static Property Start = new Property(2, String.class, "start", false, "START");
        public final static Property End = new Property(3, String.class, "end", false, "END");
    };


    public DownloadEntityDao(DaoConfig config) {
        super(config);
    }
    
    public DownloadEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DOWNLOAD_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: Id
                "\"THREAD_ID\" TEXT," + // 1: threadId
                "\"START\" TEXT," + // 2: start
                "\"END\" TEXT);"); // 3: end
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DOWNLOAD_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DownloadEntity entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String threadId = entity.getThreadId();
        if (threadId != null) {
            stmt.bindString(2, threadId);
        }
 
        String start = entity.getStart();
        if (start != null) {
            stmt.bindString(3, start);
        }
 
        String end = entity.getEnd();
        if (end != null) {
            stmt.bindString(4, end);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DownloadEntity entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String threadId = entity.getThreadId();
        if (threadId != null) {
            stmt.bindString(2, threadId);
        }
 
        String start = entity.getStart();
        if (start != null) {
            stmt.bindString(3, start);
        }
 
        String end = entity.getEnd();
        if (end != null) {
            stmt.bindString(4, end);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DownloadEntity readEntity(Cursor cursor, int offset) {
        DownloadEntity entity = new DownloadEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // threadId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // start
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // end
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DownloadEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setThreadId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStart(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEnd(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DownloadEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DownloadEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
